exports.ACCESS_TOKEN_LIVE_TIME_MINUTES = process.env.ACCESS_TOKEN_LIVE_TIME_MINUTES || 15
exports.ACCESS_TOKEN_COOKIE_NAME = process.env.ACCESS_TOKEN_COOKIE_NAME || '_atk'
exports.ACCESS_TOKEN_SET_COOKIE = process.env.ACCESS_TOKEN_SET_COOKIE || 'true'

exports.REFRESH_TOKEN_LIVE_TIME_DAYS = process.env.REFRESH_TOKEN_LIVE_TIME_DAYS || 7
exports.REFRESH_TOKEN_COOKIE_NAME = process.env.REFRESH_TOKEN_COOKIE_NAME || '_rtk'
exports.REFRESH_TOKEN_COOKIE_HTTPONLY = process.env.REFRESH_TOKEN_COOKIE_HTTPONLY || 'true'
